import $ from "jquery";
import { fetchData } from "../../Utils/Requests.js";
import {
    renderContactListsWithAccounts,
    emptyAutoGeneratedElementsInForm,
} from "./FunctionsGroup.js";
import { handleSuccessResponsePostRequet } from "../../Basic/Handlers/handleResponse.js";

$(document).ready(function () {
    /**
     * ON CLICK ADD NEW GROUP*/
    $("#create-new-group-btn").click(function () {
        //1. clean the auth generated elements in the form
        emptyAutoGeneratedElementsInForm("#user-members");

        //2. get the contact users that have accounts in the whats-app
        let apiUrl = window.routeNames.contactListHasAccounts;
        fetchData(apiUrl, "GET")
            .then((response) => {
                if (response.status === 200) {
                    renderContactListsWithAccounts(response.data);
                } else {
                }
            })
            .catch((xhr, status, error) => {
                // Extract detailed error information
                let errorMessage = "An error occurred while fetching data.";
                errorMessage = xhr.responseJSON.message;
                console.log(xhr.status);
            });

        //3. display the modal
        $("#add-group-modal").removeClass("hidden").addClass("block");
    });

    /**
     * ON CLOASE THE MODAL
     */
    $("[data-modal-hide='authentication-modal']").click(function () {
        $("#add-group-modal").removeClass("block").addClass("hidden");
    });

    /**
     * SUBMIT THE CREATION NEW GROUP
     */
    $("#create-group-form").submit(function (event) {
        event.preventDefault();
        let apiUrl = window.routeNames.groupsStore;
        fetchData(apiUrl, "POST", $(this).serialize())
            .then((response) => {
                if (response.status === 200) {
                    //1. manage the response message and data
                    handleSuccessResponsePostRequet(
                        response.status,
                        response.message,
                        4000,
                        true,
                        true,
                        "toast-bottom-center",
                        response.data,
                        "#add-group-modal",
                        "#create-group-form",
                        ".error-message"
                    );
                } else {
                    // display the error message
                }
            })
            .catch((xhr, status, error) => {
                if (xhr.status === 422) {
                    var errors = xhr.responseJSON.errors;
                    displayValidationErrorsFields(errors);
                }
            });
    });
});
