export function renderContactListsWithAccounts(contactLists) {
    let usersContainer = $("#user-members"); // The container to hold the chats

    // Loop through the chats and append them to the container
    contactLists.forEach((contact) => {
        console.log(contact.user_account.id);
        usersContainer.append(
            $("<option></option>")
                .val(contact.user_account.id)
                .text(contact.first_name)
        );
    });
}

export function emptyAutoGeneratedElementsInForm(containerClass) {
    let usersContainer = $(containerClass);
    usersContainer.empty();
}
